### ISSUE TITLE
Suggestion: Add file size on rollover

### ISSUE THREAD

**Issue by a7hybnj2** [Jelmerro/crossdirstat#4]
This is great. I had used 'SpaceSniffer' in windows and really liked it. This is close enough to satisfy my on OSX.

My suggestion is to add the size of the file block on rollover. You already display the file name so I would guess maybe underneath the file name or maybe at the end.

This would help greatly in determining the individual file sizes since the 'show colors' option still just lumps file types together.

**Comment by Jelmerro** [comment]
First of all thanks for the suggestion. I am going to assume that you meant to show the file size when hovering over a square in the visual tab, which is absolutely something that I want to add.

**Comment by a7hybnj2** [comment]
@Jelmerro yes, that is exactly what I meant. Cool, I look forward to pulling an update someday.

**Comment by Jelmerro** [comment]
I have made a new release with updated dependencies and with this suggestion added :smiley:
