### ISSUE TITLE
1.3.0 and 1.4.0 cannot be opened on Mac

### ISSUE THREAD

**Issue by a7hybnj2** [Jelmerro/crossdirstat#6]
Hi, really like this utility! I have been using 1.2.0 for a long time and only recently realized there was 1.4.0 available. I thought 'why not upgrade'... Well, I tried to run it and got an error to the effect of 'this cannot be opened'. So, I tried 1.3.0 and got the same error. I then re-downloaded the 1.2.0 and everything worked fine. Looking at the change log I don't NEED to update but I thought I would let you know...

If you need me to test any builds or compile something let me know and I can try to help out.

```
macOS 10.15.7 (19H2)
```

**Comment by Jelmerro** [comment]
Can you check if [this](https://github.com/Jelmerro/Vieb/issues/87) is similar to your issue? It seems that electron builder has issues with generating the zip file. If it's the same issue, I'll apply the same workaround that I did for Vieb to crossdirstat.

**Comment by a7hybnj2** [comment]
Yes, that appears to be similar. I did the same unzip test and got...

```
~/Downloads ▶︎︎ unzip crossdirstat-1.4.0-mac.zip 
Archive:  crossdirstat-1.4.0-mac.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of crossdirstat-1.4.0-mac.zip or
        crossdirstat-1.4.0-mac.zip.zip, and cannot find crossdirstat-1.4.0-mac.zip.ZIP, period.
~/Downloads ▶︎︎ 
```

**Comment by Jelmerro** [comment]
Alright, I have applied the same fix to crossdirstat and have created a pre-release that you can download [here](https://github.com/Jelmerro/crossdirstat/releases/tag/1.5.0-dev), let me know if that works.

**Comment by a7hybnj2** [comment]
Success! Worked great.

**Comment by Jelmerro** [comment]
Great, good to hear, I'll close the issue and make a proper 1.5.0 release later today.
